### ISSUE TITLE
Doesn't connect with nested subdomains 

### ISSUE THREAD

**Issue by Cerinthus2** [GrakovNe/lissen-android#5] opened 2024-10-26 15:50 UTC
It doesn't connect with nested subdomains. Eg a url of the format http://sub.sub.domain.com:3333 doesn't connect

**Comment by GrakovNe** [comment] 2024-10-26 23:54
Could you please provide additional data for reproducing the issue? I'd also appreciate guest access to the server to help replicate the bug.

You're also welcome to check if the issue was resolved in [version 1.0.3](https://github.com/GrakovNe/lissen-android/releases/tag/1.0.3), as I addressed one of the connection bugs in this release.

**Comment by MrGreenTea** [comment] 2024-10-27 14:42
I have a domain like https://audiobooks.private.domain.com and it works without issue... I use the default 443 port of https :)

**Comment by Cerinthus2** [comment] 2024-10-27 14:55
1.0.3 resolves it.

Cheers.

**Comment by GrakovNe** [comment] 2024-10-27 17:01
Thank you much for the report! I hope that you satisfied the app

Issue is closing due to fix is confirmed

**Closed by GrakovNe** 2024-10-27 17:01 UTC
Labels: Showstopper
